# docker-compose.yml (solo snippet)
services:
  db:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_USER: helppro
      POSTGRES_PASSWORD: secretpwd
      POSTGRES_DB: helppro
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
