# docker-compose.yml (solo snippet)
version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: helppro
      POSTGRES_PASSWORD: secretpwd
      POSTGRES_DB: helppro
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
